services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn MrProject.wsgi"
    envVars:
      - key: SECRET_KEY
        value: "django-insecure-$$wzd9mm=&*%kvp8ys2&mpad(d-hypuxwh5^xdybks1z9id^42"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgres://user:pass@host:5432/mydb"