# Generated by Django 5.1.7 on 2026-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
