# Generated by Django 5.1.7 on 2026-04-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_match_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('university_id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='dashboard.match')),
            ],
            options={
                'unique_together': {('university_id', 'match')},
            },
        ),
    ]
